package org.salemelrahal.enyo.explore;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.actions.IAction;
import bothack.actions.Navigation;
import bothack.actions.Navigation.IPath;
import bothack.bot.IGame;
import bothack.bot.Hunger;
import bothack.bot.dungeon.Branch;
import org.salemelrahal.enyo.action.PrioritizedAction;
import org.salemelrahal.enyo.util.MapUtil;
import org.salemelrahal.enyo.item.ItemInInventory;

global org.slf4j.Logger logger;

rule "Explore current level"
when
	$game : IGame($player : player)
then
	insertLogical(PrioritizedAction.create(0 ,Navigation.explore($game, Branch.MAIN), "Doing main branch by default...."));
end

rule "Explore sokoban level"
when
	$game : IGame($player : player, player.experienceLevel() > 7)
then
	insertLogical(PrioritizedAction.create(1 ,ActionsComplex.doSokoban($game), "Doing sokoban branch by default...."));
end
