package org.salemelrahal.drhack.flatten;

import bothack.bot.IGame;
import bothack.bot.items.IItem;
import org.salemelrahal.drhack.item.ItemOnTile;

global org.slf4j.Logger logger;

rule "Insert item on floor"
when
	$game : IGame( $tile : currentLevel.at(player))
	$item : IItem() from $tile.items()
then
	logger.info("Item on floor: " + $item.type().name() + "["+$item.name()+"]");
	insert(ItemOnTile.create($item));
end