package org.salemelrahal.drhack.flatten;

import bothack.bot.IGame;
import org.salemelrahal.drhack.enemy.Enemy;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;


global org.slf4j.Logger logger;

rule "Insert non-{peaceful,friendly} Monsters as enemies"
when
	$game : IGame($player : player)
	$monster : IMonster( !this.isPeaceful(), !this.isFriendly(), !Position.areAdjacent($player, this)) from $game.currentLevel.monsters.values
then
	insertLogical(new Enemy($monster, false));
end


rule "Insert adjacent non-{peaceful,friendly} Monsters as enemies"
when
	$game : IGame($player : player)
	$monster : IMonster( !this.isPeaceful(), !this.isFriendly(), Position.areAdjacent($player, this)) from $game.currentLevel.monsters.values
then
	insertLogical(new Enemy($monster, true));
end