package org.salemelrahal.drhack.hunger;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.drhack.action.PrioritizedAction;
import org.salemelrahal.drhack.item.ItemInInventory;
import org.salemelrahal.drhack.item.ItemOnTile;
import org.salemelrahal.drhack.state.InShop;
import org.salemelrahal.drhack.state.Stoning;
import bothack.bot.items.ItemType;

global org.slf4j.Logger logger;

rule "Recognize Stoning"
when
	IGame(player.isStoning())
then
	insertLogical(new Stoning());
end