package org.salemelrahal.drhack.pickup;

import bothack.actions.Actions;
import bothack.actions.IAction;
import bothack.actions.NavOption;
import bothack.bot.IGame;
import bothack.bot.dungeon.RoomType;
import bothack.bot.Hunger;
import bothack.bot.Direction;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;
import bothack.bot.items.IItemType;
import bothack.bot.items.ItemType;
import bothack.bot.items.IItem;
import org.salemelrahal.drhack.util.MapUtil;
import org.salemelrahal.drhack.action.PrioritizedAction;
import org.salemelrahal.drhack.item.ItemOnTile;
import org.salemelrahal.drhack.state.InShop;

global org.slf4j.Logger logger;


rule "Pick up food ration outside of a shop"
when
	ItemOnTile($food : item,  item.type() == ItemType.byName("food ration"))
	not InShop()
then
	insert(PrioritizedAction.create(3 , Actions.PickUp($food.label()), "picking up food ration outside of a shop"));
end

rule "Pick up lichen corpse outside of a shop"
when
	ItemOnTile($corpse : item, item.type() == ItemType.byName("lichen corpse"))
	not InShop()
then
	insert(PrioritizedAction.create(3 , Actions.PickUp($corpse.label()), "picking up lichen corpse outside of a shop"));
end