package org.salemelrahal.drhack.hunger;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.drhack.action.PrioritizedAction;
import org.salemelrahal.drhack.item.ItemInInventory;
import org.salemelrahal.drhack.item.ItemOnTile;
import org.salemelrahal.drhack.state.LowHealth;

global org.slf4j.Logger logger;

rule "Mark low health"
when
	IGame($player : player, player.HP() < 10 || (((double)player.HP())/player.maxHP()) < .45)
then
	insertLogical(new LowHealth());
end

rule "Debug low health"
when
	IGame($player : player, player.HP() < 10)
then
	logger.info("player has less than ten health " + $player.HP() + "," + $player.maxHP());
end

rule "Debug low health2"
when
	IGame($player : player, (((double)player.HP())/player.maxHP()) < .45)
then
	logger.info("player has less 45% health " + $player.HP() + "," + $player.maxHP() );
end

rule "Healthy"
when
	IGame($player : player, player.HP() >= 10 && (((double)player.HP())/player.maxHP()) >= .45)
then
	logger.info("player is healthy " + $player.HP() + "," + $player.maxHP() );
end