import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.state.Ill;
import org.salemelrahal.enyo.action.ReasonedAction;

global org.slf4j.Logger logger;

rule "Recognize food poisoning"
when
	IGame($player : player, player.isIll())
then
	insert(new Ill());
end