package org.salemelrahal.enyo.attack;

import bothack.actions.Actions;
import org.salemelrahal.enyo.enemy.Enemy;
import bothack.bot.IGame;
import bothack.bot.Hunger;
import bothack.bot.Direction;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;
import org.salemelrahal.enyo.action.ReasonedAction;
import org.salemelrahal.enyo.util.MapUtil;
import org.salemelrahal.enyo.state.OnElbereth;
import org.salemelrahal.enyo.state.OnEngravableTile;
import org.salemelrahal.enyo.item.ItemInInventory;
import org.salemelrahal.enyo.fact.PathToAdvantageousTile;

global org.slf4j.Logger logger;

rule "Engrave with finger proactively when about to fact many enemies" 
when
	$first : Enemy(isAwake(), respectsElbereth())
	Enemy(isAwake(), respectsElbereth(),this != $first)
	not OnElbereth()
	OnEngravableTile()
	IGame(canEngrave())
	not ItemInInventory($slot : slot, item.name().contains("wand of fire"))
then
	insertLogical(ReasonedAction.create(Actions.EngraveOverwriting('-', "Elbereth"), "Engraving elbereth with finger proactively "));
end


rule "Engrave with WoF proactively when about to fact many enemies" 
when
	$first : Enemy(isAwake(), respectsElbereth())
	Enemy(isAwake(), respectsElbereth(),this != $first)
	not OnElbereth()
	OnEngravableTile()
	IGame(canEngrave())
	ItemInInventory($slot : slot, item.name().contains("wand of fire"))
then
	insertLogical(ReasonedAction.create(Actions.EngraveOverwriting($slot, "Elbereth"), "Engraving elbereth with wand of fire proactively"));
end