package org.salemelrahal.enyo.attack;

import bothack.actions.Actions;
import org.salemelrahal.enyo.action.Move;
import bothack.bot.IGame;
import bothack.bot.Hunger;
import bothack.bot.Direction;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;

global org.slf4j.Logger logger;

rule "Engulfed"
when
	$game : IGame($player : player, player.isEngulfed())
then
	insertLogical(new Move(Direction.E));
end