package org.salemelrahal.enyo.attack;

import bothack.actions.Actions;
import org.salemelrahal.enyo.action.Move;
import bothack.bot.IGame;
import bothack.bot.Hunger;
import bothack.bot.Direction;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;
import org.salemelrahal.enyo.action.ReasonedAction;

global org.slf4j.Logger logger;

rule "Engulfed"
when
	$game : IGame($player : player, player.isEngulfed())
then
	insertLogical(ReasonedAction.create(new Move(Direction.E), "moving to attack engulfer"));
end