package org.salemelrahal.enyo.status.stoning;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.item.ItemInInventory;
import org.salemelrahal.enyo.item.ItemOnTile;
import org.salemelrahal.enyo.state.InShop;
import bothack.bot.items.ItemType;
import org.salemelrahal.enyo.action.Eat;
import org.salemelrahal.enyo.action.Pray;

global org.slf4j.Logger logger;

rule "Eat lizard corpse when stoning"
when
	Stoning()
	ItemInInventory($slot : slot, $item : item, item.type() == ItemType.byName("lizard corpse"))
then
	insertLogical(new Eat($slot));
end


rule "Pray when stoning"
when
	IGame(canPray())
	Stoning()
then
	insertLogical(new Pray());
end