package org.salemelrahal.enyo.status.stoning;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.action.ReasonedAction;
import org.salemelrahal.enyo.item.ItemInInventory;
import org.salemelrahal.enyo.item.ItemOnTile;
import org.salemelrahal.enyo.state.InShop;
import org.salemelrahal.enyo.state.Stoning;
import bothack.bot.items.ItemType;

global org.slf4j.Logger logger;

rule "Recognize Stoning"
when
	IGame(player.isStoning())
then
	insertLogical(new Stoning());
end