package org.salemelrahal.enyo.flatten;

import bothack.bot.IGame;
import org.salemelrahal.enyo.enemy.Enemy;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;


global org.slf4j.Logger logger;

rule "Insert non-{peaceful,friendly} Monsters as enemies"
when
	$game : IGame($player : player)
	$monster : IMonster( !this.isPeaceful(), !this.isFriendly(), !Position.areAdjacent($player, this)) from $game.currentLevel.monsters.values
then
	logger.info("Inserting non-adjacent monster " + ($monster.type() == null ? "?" : $monster.type().name()));
	insertLogical(new Enemy($game, $monster, false));
end


rule "Insert adjacent non-{peaceful,friendly} Monsters as enemies"
when
	$game : IGame($player : player)
	$monster : IMonster( !this.isPeaceful(), !this.isFriendly(), Position.areAdjacent($player, this)) from $game.currentLevel.monsters.values
then
	logger.info("Inserting adjacent monster " + ($monster.type() == null ? "?" : $monster.type().name()));
	insertLogical(new Enemy($game, $monster, true));
end