package org.salemelrahal.enyo.flatten;

import bothack.bot.IGame;
import bothack.bot.items.IItem;
import java.util.Map.Entry;
import org.salemelrahal.enyo.item.ItemInInventory;
import org.salemelrahal.enyo.item.RangedWeapon;

global org.slf4j.Logger logger;

rule "Parse Ranged Weapon"
when
	$item : ItemInInventory($slot : slot, item.name().contains("dagger"))
then
	insert(new RangedWeapon($slot)); //TODO:change this to RangedWeapon($item) 
end