import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.state.Polymorphed;
import org.salemelrahal.enyo.action.PrioritizedAction;

global org.slf4j.Logger logger;

rule "Wait when polymorphed"
when
	IGame($player : player)
	Polymorphed() //TODO: care about type
then
	insertLogical(PrioritizedAction.create(13 , Actions.Wait(), "waiting to not be polymorphed"));
end
