package org.salemelrahal.enyo.status.polymorphed;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.state.Polymorphed;
import org.salemelrahal.enyo.action.Wait;

global org.slf4j.Logger logger;

rule "Wait when polymorphed"
when
	IGame($player : player)
	Polymorphed() //TODO: care about type
then
	insertLogical(new Wait());
end
