package org.salemelrahal.enyo.status.polymorphed;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.state.Polymorphed;
import org.salemelrahal.enyo.action.ReasonedAction;

global org.slf4j.Logger logger;

rule "Recognize polymorphism"
when
	IGame($player : player, player.polymorphed() != null)
then
	insertLogical(new Polymorphed($player.polymorphed()));
end