package org.salemelrahal.enyo.hunger;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.action.PrioritizedAction;
import org.salemelrahal.enyo.item.ItemInInventory;
import org.salemelrahal.enyo.item.ItemOnTile;
import org.salemelrahal.enyo.state.LowHealth;
import org.salemelrahal.enyo.state.MediumHealth;
import org.salemelrahal.enyo.state.Panic;

global org.slf4j.Logger logger;


rule "Mark medium health"
when
	IGame($player : player, player.HP() < 10 || (((double)player.HP())/player.maxHP()) < .75)
then
	insertLogical(new MediumHealth());
end

rule "Mark low health"
when
	IGame($player : player, player.HP() < 10 || (((double)player.HP())/player.maxHP()) < .45)
then
	insertLogical(new LowHealth());
end

rule "Mark panic"
when
	IGame($player : player, player.HP() < 5 || (((double)player.HP())/player.maxHP()) < .25)
then
	insertLogical(new Panic());
end