package org.salemelrahal.enyo.panic;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.action.ReasonedAction;
import org.salemelrahal.enyo.item.ItemInInventory;
import org.salemelrahal.enyo.item.ItemOnTile;
import org.salemelrahal.enyo.state.Panic;
import bothack.bot.Direction;
import org.salemelrahal.enyo.enemy.Enemy;
import org.salemelrahal.enyo.action.ZapWandAtMonster;


global org.slf4j.Logger logger;

rule "Zap random wands when panicced"
when
	$game : IGame($player : player)
	Panic()
	Enemy($monster : target, isMarked())
	ItemInInventory($slot : slot, $item : item, $item.name().contains("wand"), $item.type() == null)
then
	insertLogical(ReasonedAction.create(new ZapWandAtMonster($slot, $player, $monster), "zapping adjacent marked monster " + $monster.type().name() + " with " + $item.name()));
end