package org.salemelrahal.enyo.status.blindness;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.state.Blind;
import org.salemelrahal.enyo.action.ReasonedAction;
import org.salemelrahal.enyo.action.Wait;

global org.slf4j.Logger logger;

rule "Wait when blind"
when
	IGame($player : player)
	Blind() //TODO: care about type (external or not)
then
	insert(ReasonedAction.create(new Wait(), "waiting to not be blind"));
end
