package org.salemelrahal.enyo.status.blindness;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.state.Blind;

global org.slf4j.Logger logger;

rule "Recognize blindness"
when
	IGame($player : player, player.isBlind())
then
	insert(new Blind());
end