import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.state.Lycanthropic;
import org.salemelrahal.enyo.item.ItemInInventory;
import org.salemelrahal.enyo.action.PrioritizedAction;
import bothack.bot.items.ItemType;

global org.slf4j.Logger logger;

rule "Recognize lycanthropy"
when
	IGame($player : player, player.hasLycantrophy())
then
	insertLogical(new Lycanthropic());
end