package org.salemelrahal.enyo.tile;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.enyo.item.ItemInInventory;
import org.salemelrahal.enyo.item.ItemOnTile;
import org.salemelrahal.enyo.state.OnElbereth;
import org.salemelrahal.enyo.state.OnEngravableTile;
import org.salemelrahal.enyo.state.OnFountain;
import bothack.bot.dungeon.Feature;

global org.slf4j.Logger logger;

rule "Found Altar"
when
	IGame(currentLevel.at(player).hasElbereth())
then
	insertLogical(new OnElbereth());
end