package org.salemelrahal.drhack.attack;

import bothack.bot.IGame;
import org.salemelrahal.drhack.enemy.Enemy;
import bothack.bot.monsters.IMonster;
import bothack.actions.Actions;
import bothack.bot.Direction;
import org.salemelrahal.drhack.action.PrioritizedAction;
import bothack.bot.dungeon.Feature;
import bothack.actions.Navigation;



global org.slf4j.Logger logger;

rule "Move towards marked enemy that is not adjacent"
when
	$game : IGame($player : player, currentLevel.at(player).feature() != Feature.DOOR_OPEN)
	Enemy($monster : target, isMarked(), !isAdjacent())
then
	insert(PrioritizedAction.create(8 , Navigation.navigate($game, $monster).step(), "move towards monster " + $monster.type().name()));
end
