package org.salemelrahal.drhack.attack;

import bothack.actions.Actions;
import bothack.bot.IGame;
import bothack.bot.Hunger;
import bothack.bot.Direction;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;
import org.salemelrahal.drhack.action.PrioritizedAction;

global org.slf4j.Logger logger;

rule "Engulfed"
when
	$game : IGame($player : player, player.isEngulfed())
then
	insert(PrioritizedAction.create(10 , Actions.Move(Direction.E), "moving to attack engulfer"));
end