package org.salemelrahal.drhack.attack;

import bothack.actions.Actions;
import org.salemelrahal.drhack.enemy.Enemy;
import bothack.bot.IGame;
import bothack.bot.Hunger;
import bothack.bot.Direction;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;
import org.salemelrahal.drhack.action.PrioritizedAction;
import org.salemelrahal.drhack.util.MapUtil;
import org.salemelrahal.drhack.state.OnElbereth;
import org.salemelrahal.drhack.state.OnEngravableTile;
import org.salemelrahal.drhack.item.ItemInInventory;
import org.salemelrahal.drhack.fact.PathToAdvantageousTile;
import org.salemelrahal.drhack.state.OnAdvantageousTile;

global org.slf4j.Logger logger;


rule "Mark advantageous tile"
when
	IGame(MapUtil.isAdvantageous(this, currentLevel.at(player)))
then
	insertLogical(new OnAdvantageousTile());
end


rule "Move to advantageous tile when about to face many enemies" 
when
	$first : Enemy(isAwake())
	Enemy(isAwake(),  this != $first)
	not OnElbereth()
	not OnAdvantageousTile()
	PathToAdvantageousTile($path : path != null)
then
	insertLogical(PrioritizedAction.create(17 , $path.step(), "move towards advantageous tile " + $path.step()));
end