package org.salemelrahal.drhack.hunger;

import bothack.actions.Actions;
import bothack.actions.ActionsComplex;
import bothack.bot.IGame;
import bothack.bot.items.IItem;
import bothack.bot.Hunger;
import java.util.Map.Entry;
import org.salemelrahal.drhack.action.PrioritizedAction;
import org.salemelrahal.drhack.item.ItemInInventory;
import org.salemelrahal.drhack.item.ItemOnTile;
import org.salemelrahal.drhack.state.OnElbereth;
import org.salemelrahal.drhack.state.OnEngravableTile;

global org.slf4j.Logger logger;

rule "Parse Elbereth"
when
	IGame(currentLevel.at(player).hasElbereth())
then
	insertLogical(new OnElbereth());
end

rule "Parse Engravable Tile"
when
	IGame(currentLevel.at(player).isEngravable())
then
	insertLogical(new OnEngravableTile());
end