package org.salemelrahal.enyo.pickup;

import bothack.actions.Actions;
import bothack.actions.IAction;
import bothack.actions.NavOption;
import bothack.bot.IGame;
import bothack.bot.dungeon.RoomType;
import bothack.bot.Hunger;
import bothack.bot.Direction;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;
import bothack.bot.items.IItemType;
import bothack.bot.items.ItemType;
import bothack.bot.items.IItem;
import org.salemelrahal.enyo.util.MapUtil;
import org.salemelrahal.enyo.item.ItemOnTile;
import org.salemelrahal.enyo.state.InShop;
import org.salemelrahal.enyo.action.PickUpItem;

global org.slf4j.Logger logger;

rule "Pick up dagger outside of a shop"
when
	ItemOnTile($dagger : item,  item.name().contains("dagger"))
	not InShop()
then
	insertLogical(new PickUpItem($dagger));
end