package org.salemelrahal.enyo.pickup;

import bothack.actions.Actions;
import bothack.actions.IAction;
import bothack.actions.NavOption;
import bothack.bot.IGame;
import bothack.bot.dungeon.RoomType;
import bothack.bot.Hunger;
import bothack.bot.Direction;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;
import bothack.bot.items.IItemType;
import bothack.bot.items.ItemType;
import bothack.bot.items.IItem;
import org.salemelrahal.enyo.util.MapUtil;
import org.salemelrahal.enyo.item.ItemOnTile;
import org.salemelrahal.enyo.state.InShop;
import org.salemelrahal.enyo.action.PickUpItem;

global org.slf4j.Logger logger;


rule "Pick up food ration outside of a shop"
when
	ItemOnTile($food : item,  item.type() == ItemType.byName("food ration"))
	not InShop()
then
	insertLogical(new PickUpItem($food));
end

rule "Pick up lichen corpse outside of a shop"
when
	ItemOnTile($corpse : item, item.type() == ItemType.byName("lichen corpse"))
	not InShop()
then
	insertLogical(new PickUpItem($corpse));
end

rule "Pick up lizard corpse outside of a shop"
when
	ItemOnTile($corpse : item, item.type() == ItemType.byName("lizard corpse"))
	not InShop()
then
	insertLogical(new PickUpItem($corpse));
end