package org.salemelrahal.enyo.pickup;

import bothack.bot.items.ItemType;
import org.salemelrahal.enyo.action.ReasonedAction;
import org.salemelrahal.enyo.item.ItemOnTile;
import org.salemelrahal.enyo.state.InShop;

global org.slf4j.Logger logger;

rule "Pick up gold"
when
	ItemOnTile($gold : item,  item.type() == ItemType.byName("gold piece"))
	not InShop()
then
	insertLogical(ReasonedAction.create(Actions.PickUp($gold.label()), "picking up gold"));
end