package org.salemelrahal.enyo.pickup;

import bothack.actions.Actions;
import bothack.actions.IAction;
import bothack.actions.NavOption;
import bothack.bot.IGame;
import bothack.bot.dungeon.RoomType;
import bothack.bot.Hunger;
import bothack.bot.Direction;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;
import bothack.bot.items.IItemType;
import bothack.bot.items.ItemType;
import bothack.bot.items.IItem;
import org.salemelrahal.enyo.util.MapUtil;
import org.salemelrahal.enyo.item.ItemOnTile;
import org.salemelrahal.enyo.state.InShop;
import org.salemelrahal.enyo.action.item.PickUpWeapon;
import org.salemelrahal.enyo.action.monster.MoveTowardsEnemy;

global org.slf4j.Logger logger;

rule "Pick up dagger outside of a shop"
when
	$item : ItemOnTile(item.name().contains("dagger"))
	not InShop()
then
	insertLogical(new PickUpWeapon($item));
end

rule "Pick up weapons when you're on the way to kill a monster"
when
	move : MoveTowardsEnemy()
	PickUpWeapon()
then
	delete(move);
end