package org.salemelrahal.enyo.pickup;

import bothack.actions.Actions;
import bothack.actions.IAction;
import bothack.actions.NavOption;
import bothack.bot.IGame;
import bothack.bot.dungeon.RoomType;
import bothack.bot.Hunger;
import bothack.bot.Direction;
import bothack.bot.monsters.IMonster;
import bothack.bot.Position;
import bothack.bot.items.IItemType;
import bothack.bot.items.ItemType;
import bothack.bot.items.IItem;
import org.salemelrahal.enyo.util.MapUtil;
import org.salemelrahal.enyo.item.ItemOnTile;
import org.salemelrahal.enyo.state.InShop;
import org.salemelrahal.enyo.action.item.PickUpWeapon;
import org.salemelrahal.enyo.action.item.TargetItemAction;
import org.salemelrahal.enyo.action.monster.MoveTowardsEnemy;

global org.slf4j.Logger logger;

rule "Deal with high priority items"
when
	TargetItemAction(target.getPriority() != null, $priority : target.getPriority())
	$low : TargetItemAction(target.getPriority() != null, target.getPriority() < $priority)
then
	delete($low);
end